"""Initial migration

Revision ID: 9d2b97c1910c
Revises: 
Create Date: 2025-05-29 00:14:00.036849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d2b97c1910c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comments_post'))

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_media_uploaded_by'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_posts_author'))
        batch_op.drop_index(batch_op.f('idx_posts_slug'))
        batch_op.drop_index(batch_op.f('idx_posts_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_author'), ['author_id'], unique=False)

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_media_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.alter_column('media',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_comments_post'), ['post_id'], unique=False)

    # ### end Alembic commands ###
