"""add table field_data

Revision ID: 3a3471a46eef
Revises: 499331b8a17f
Create Date: 2024-08-07 09:12:31.635636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3471a46eef'
down_revision = '499331b8a17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_value', sa.String(length=100), nullable=True),
    sa.Column('completed_work_id', sa.Integer(), nullable=False),
    sa.Column('permissible_work_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['completed_work_id'], ['nrega_completed_works.id'], ),
    sa.ForeignKeyConstraint(['input_id'], ['input_parameters.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['nrega_panchayats.id'], ),
    sa.ForeignKeyConstraint(['permissible_work_id'], ['nrega_permissible_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_data')
    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
