"""modified input_parameters

Revision ID: 44a7952c3c62
Revises: 3a3471a46eef
Create Date: 2024-08-16 16:36:17.461727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a7952c3c62'
down_revision = '3a3471a46eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('input_parameters', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('label')

    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
