"""not null plant_type

Revision ID: 67b23d6932ad
Revises: fc7043867e46
Create Date: 2024-10-17 17:27:33.971586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b23d6932ad'
down_revision = 'fc7043867e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_types', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
